##
## Fastlane configuration for the Nevis Mobile Authentication SDK Example App iOS application.
## See https://docs.fastlane.tools
##

require "securerandom"

default_platform(:ios)

project = "NevisExampleApp.xcodeproj"
scheme = "NevisExampleApp"
app_identifier = "ch.nevis.mobile.authentication.sdk.ios.example"
match_type = "adhoc"
config_plist = File.expand_path("../NevisExampleApp/Resources/ConfigAuthenticationCloud.plist")
output_dir = File.expand_path("output/")
display_name = "Nevis Mobile Authentication SDK Example App iOS"

keychain_password = SecureRandom.base64
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

def ensure_temp_keychain(name, password)
	delete_temp_keychain(name)
	create_temp_keychain(name, password)
end

def create_temp_keychain(name, password)
	create_keychain(
		name:,
		password:,
		unlock: true,
		timeout: 0,
		lock_when_sleeps: true
	)
end

def delete_temp_keychain(name)
	delete_keychain(name:) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def report_on_success(message)
	slack(
		message: "#{message}\nCheck build logs: #{ENV['CURRENT_BUILD_URL']}",
		slack_url: ENV["SLACK_WEBHOOK_URL"]
	) if ENV["SLACK_WEBHOOK_URL"]
end

def report_on_error(message, exception)
	slack(
		message: "#{message}\nCheck build logs: #{ENV['CURRENT_BUILD_URL']}",
		slack_url: ENV["SLACK_WEBHOOK_URL"],
		success: false,
		attachment_properties: {
			fields: [
				{
					title: "Error message",
					value: exception.to_s,
					short: false
				}
			]
		}
	) if ENV["SLACK_WEBHOOK_URL"]
	UI.user_error!(exception.to_s)
end

platform :ios do
	desc "Build and distribute the application"
	lane :main do
		keychain_name = ENV["TEMP_KEYCHAIN_NAME"]
		ensure_temp_keychain(
			keychain_name,
			keychain_password
		)

		update_config(host_name: ENV["HOST_NAME"])

		build_number = ENV["BUILD_NUMBER"] || get_build_number
		version = get_version_number
		increment_build_number(build_number:)

		UI.message("Distributing #{display_name} #{version} (#{build_number}) 📦")

		match(
			type: match_type,
			readonly: true,
			app_identifier:,
			git_url: ENV["MATCH_GIT_URL"],
			git_branch: "main",
			keychain_name:,
			keychain_password:
		)

		profile_name = ENV["sigh_#{app_identifier}_#{match_type}_profile-name"]
		update_code_signing_settings(
			path: project,
			build_configurations: ["Release"],
			use_automatic_signing: false,
			team_id: ENV["DEVELOPER_PORTAL_TEAM_ID"],
			code_sign_identity: ENV["CODE_SIGNING_IDENTITY"],
			profile_name:
		)

		gym(
			project:,
			scheme:,
			configuration: "Release",
			clean: true,
			skip_profile_detection: true,
			disable_package_automatic_updates: true,
			export_method: "ad-hoc",
			export_options: {
				provisioningProfiles: {
					app_identifier => ENV["PROVISIONING_PROFILE_SPECIFIER"]
				}
			},
			output_directory: "#{output_dir}/builds",
			xcargs: "OTHER_CODE_SIGN_FLAGS=\"--keychain=#{keychain_name}\""
		)

		firebase_app_distribution(
			app: ENV["FIREBASE_APP_ID"],
			ipa_path: "#{output_dir}/builds/#{scheme}.ipa",
			groups: "developers, internal-testers, presales"
		)

		add_git_tag(tag: "release/#{version}/#{build_number}", message: "[Fastlane] #{display_name} #{version} (#{build_number})")
		push_git_tags

		delete_temp_keychain(keychain_name)
		report_on_success("#{display_name} build is completed: #{version} (#{build_number}) ✅")
	rescue => e
		report_on_error("#{display_name} build failed ❌", e)
	end

	desc "Build the application"
	lane :pr do
		gym(
			project:,
			scheme:,
			configuration: "Release",
			clean: true,
			skip_codesigning: true,
			skip_profile_detection: true,
			disable_package_automatic_updates: true,
			skip_archive: true,
			skip_package_ipa: true
		)
	end

	##
	## Private Lanes
	##

	private_lane :update_config do |options|
		host_name = options[:host_name]

		update_plist(
			plist_path: config_plist,
			block: proc do |plist|
				plist["login"] = {
					loginRequestURL: "https://#{host_name}.mauth.nevis.cloud/_app/auth/pwd"
				}
				plist["sdk"] = {
					hostName: "#{host_name}.mauth.nevis.cloud"
				}
			end
		)
	end
end
