name: Main Branch Commit

on:
  push:
    branches: [ 'main' ]
  schedule:
    # At 5:30 am on the 1st and 15th day of the month (every two weeks)
    - cron: '30 5 1,15 * *'
  workflow_dispatch:
    inputs:
      runner_type:
        type: choice
        required: true
        description: "Runner type"
        default: "self-hosted"
        options:
          - "self-hosted"
          - "macos-15"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  MATCH_GIT_URL: ${{ vars.MATCH_GIT_URL }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
  CODE_SIGNING_IDENTITY: ${{ secrets.CODE_SIGNING_IDENTITY }}
  PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
  TEMP_KEYCHAIN_NAME: ${{ vars.TEMP_KEYCHAIN_NAME }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  HOST_NAME: ${{ vars.HOST_NAME }}
  SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}

  CURRENT_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  RUBY_VERSION: 3.1
  XCODE_VERSION: 16.2

jobs:
  main:
    runs-on: "${{ github.event.inputs.runner_type || 'self-hosted' }}"

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - name: Checkout Project
        uses: actions/checkout@v4

      # Ensure correct Xcode version is installed.
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      # Set Ruby version and Cache RubyGem dependencies
      - name: Cache RubyGem Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      # Generate build number
      - name: Generate Build Number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ env.GITHUB_TOKEN }}

      # Build & Distribute
      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'main'
