name: Verify Pull Request

on:
  pull_request:
    branches: [ 'main' ]
    types: [opened, edited, synchronize, reopened]

env:
  XCODE_VERSION: '15.0.1'

jobs:
  pr:
    runs-on: macos-13

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - name: Checkout Project
        uses: actions/checkout@v3

      # Ensure correct Xcode version is installed.
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      # Set Ruby version and Cache RubyGem dependencies
      - name: Cache RubyGem Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      # Build & Distribute
      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'pr'
